### 

# Admin — Products


### List products

GET {{baseUrl}}/api/admin/products HTTP/1.1
Authorization: Bearer {{apiKey}}


### 


### Create product

POST {{baseUrl}}/api/admin/products HTTP/1.1
Authorization: Bearer {{apiKey}}
Content-Type: application/json

{
  "code": "flow",
  "default_max_devices": 1,
  "description": "A test product",
  "name": "flow"
}


### 


### Update product

PATCH {{baseUrl}}/api/admin/products/{{productId}} HTTP/1.1
Authorization: Bearer {{apiKey}}
Content-Type: application/json

{
  "default_max_devices": 3,
  "name": "My Product (Updated)"
}


### 


### Archive product

PATCH {{baseUrl}}/api/admin/products/{{productId}} HTTP/1.1
Authorization: Bearer {{apiKey}}
Content-Type: application/json

{
  "status": "archived"
}


### 
